<?php

function fbs_like_fbs_plugin_info(){
  $info = array();
  $info['like'] = array(
      'name' => 'like', 
      'description' => 'Like button', 
      'defaults' => '', 
      'options_form' => '' 
  );
  
  return $info;
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function fbs_like_ctools_plugin_api($module, $api){
  if ($module == 'boxes' && $api == 'plugins') {
    return array(
        'version' => 1 
    );
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function fbs_like_boxes_plugins(){
  $info = array();
  
  $info['fbs_boxes_like'] = array(
      'title' => 'facebook social like', 
      'handler' => array(
          'class' => 'fbs_boxes_like', 
          'file' => 'fbs_boxes_like.inc', 
          'path' => drupal_get_path('module', 'fbs_like') . '/boxes', 
          'parent' => 'fbs_boxes_default' 
      ) 
  );
  
  return $info;
}
