<?php

function fbs_like_fbs_plugins_info(){
  module_load_include('inc', 'fbs_like', 'fbs_like_settings');
  $info = array();
  $info['like'] = array(
      'name' => 'like', 
      'description' => 'Like button', 
      'defaults' => _fbs_like_fb_defaults(), 
      'options_form' => _fbs_like_fb_options_form(),
      //'settings_form' => _fbs_like_d_settings_form(),
  );
  
  return $info;
}

function fbs_like_d_settings_form($settings){
  module_load_include('inc', 'fbs_like', 'fbs_like_settings');
  return _fbs_like_d_settings_form($settings);
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function fbs_like_ctools_plugin_api($module, $api){
  if ($module == 'boxes' && $api == 'plugins') {
    return array(
        'version' => 1 
    );
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function fbs_like_boxes_plugins(){
  $info = array();
  
  $info['fbs_like_boxes_like'] = array(
      'title' => 'facebook social like', 
      'handler' => array(
          'class' => 'fbs_like_box', 
          'file' => 'fbs_like_boxes.inc', 
          'path' => drupal_get_path('module', 'fbs_like'), 
          'parent' => 'fbs_boxes_default' 
      ) 
  );
  
  return $info;
}

