<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function fbs_boxes_ctools_plugin_api($module, $api){
  //boxes
  if ($module == 'boxes' && $api == 'plugins') {
    return array(
        'version' => 1 
    );
  }
}

// boxes 
/**
 * Implementation of hook_boxes_plugins().
 */
function fbs_boxes_boxes_plugins(){
  $info = array();
  
  $info['fbs_boxes_default'] = array(
      'title' => '',  // important . We dont /box-add/fbs_boxes_default
      'handler' => array(
          'class' => 'fbs_boxes_default', 
          'file' => 'fbs_boxes_default.inc', 
          'path' => drupal_get_path('module', 'fbs_boxes') . '/boxes', 
          'parent' => 'box' 
      ) 
  );

  
  $info['fbs_boxes_like_box'] = array(
      'title' => 'facebook social likebox', 
      'handler' => array(
          'class' => 'fbs_boxes_like_box', 
          'file' => 'fbs_boxes_like_box.inc', 
          'path' => drupal_get_path('module', 'fbs_boxes') . '/boxes', 
          'parent' => 'fbs_boxes_default' 
      ) 
  );
  
  return $info;
}

/**
 * Implementation of hook_theme
 */
function fbs_boxes_theme(){
  return array(
      'fbs_boxes_box' => array(
          'arguments' => array(
              'box' => NULL 
          ) 
      ) 
  );
}

/**
 * returns the fbml content of the widget
 */
function theme_fbs_boxes_box($box){
  $attrs = drupal_attributes(array_filter($box->options));
  
  /**
   * get widget type from the ctools plugin_key
   * - fbs_boxes_like -> like
   * - fbs_boxes_like_box -> like-box
   */
  $tmp = explode('_', $box->plugin_key);
  $widget_type = implode('-', array_slice($tmp, 2));
  
  return '<div class="fbs-' . $widget_type . '-widget"><fb:' . $widget_type . ' ' . $attrs . '></fb:' . $widget_type . '></div>';
}
