<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function fbs_boxes_ctools_plugin_api($module, $api){
  //boxes
  if ($module == 'boxes' && $api == 'plugins') {
    return array(
        'version' => 1 
    );
  }
}

// boxes 
/**
 * Implementation of hook_boxes_plugins().
 */
function fbs_boxes_boxes_plugins(){
  $info = array();
  $info['fbs_boxes_like_box'] = array(
      'title' => 'facebook social likebox', 
      'handler' => array(
          'class' => 'fbs_boxes_like_box', 
          'file' => 'fbs_boxes_like_box.inc', 
          'path' => drupal_get_path('module', 'fbs_boxes') . '/boxes', 
          'parent' => 'fbs_boxes_default' 
      ) 
  );
  
  return $info;
}



