<?php

function fbs_likebox_fbs_plugins_info(){
  $info = array();
  $info['likebox'] = array(
      'name' => 'likebox', 
      'description' => 'Likebox', 
  );
  return $info;
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function fbs_likebox_ctools_plugin_api($module, $api){
  if ($module == 'boxes' && $api == 'plugins') {
    return array(
        'version' => 1 
    );
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function fbs_likebox_boxes_plugins(){
  $info = array();
  
  $info['fbs_likebox_boxes_like'] = array(
      'title' => 'facebook social like-box', 
      'handler' => array(
          'class' => 'fbs_likebox_box', 
          'file' => 'fbs_likebox_boxes.inc', 
          'path' => drupal_get_path('module', 'fbs_likebox'), 
          'parent' => 'fbs_boxes_default' 
      ) 
  );
  
  return $info;
}

