<?php
//$Id

/**
 * Minimum CTools version needed.
 */
define('FBS_REQUIRED_CTOOLS_API', '1.7.1');

/**
 * Implementation of hook_ctools_plugin_api().
 */
function fbs_ctools_plugin_api($module, $api) {
  if ($module == 'fbs' && $api == 'fbs') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function fbs_ctools_plugin_directory($module, $type) {
  // Safety: go away if CTools is not at an appropriate version.
  if (!module_invoke('ctools', 'api_version', FBS_REQUIRED_CTOOLS_API)) {
    return;
  }

  if ($module =='fbs' && $type == 'plugins') {
    return 'plugins/fbs';
  }
  elseif ($type =='export_ui') {
    return 'plugins/export_ui';
  }
}

function fbs_fbs_default_presets(){
  $export = array();
  $fbs_presets = new stdClass();
  $fbs_presets->disabled = FALSE; /* Edit this to true to make a default fbs_presets disabled initially */
  $fbs_presets->api_version = 1;
  $fbs_presets->name = 'fb_like_default';
  $fbs_presets->description = 'the default ';
  $fbs_presets->widget_type = 'likebox';
  $fbs_presets->d_settings = FALSE;
  $fbs_presets->fb_settings = array(
      'layout_style' => 'button_count', 
      'show_faces' => 0, 
      'width' => '350', 
      'verb' => 'like', 
      'font' => 'verdana', 
      'color' => 'dark' 
  );  

  
  $export['fb_like_default'] = $fbs_presets;

  return $export;
}

/**
 * Load & crud functions ==============================================
 */

function fbs_fbs_presets_list(){

}

/**
 * preset loader.
 *
 * @param $name
 *   The name for this preset object.
 *
 * @return
 *   Returns a fully-loaded preset definition.
 */
function fbs_presets_load($name = NULL, $reset = FALSE) {

}

/**
 * Inserts or updates a preset object into the database.
 *
 * @param $preset
 *   The preset object to be inserted.
 *
 * @return
 *   Failure to write a record will return FALSE. Otherwise SAVED_NEW or
 *   SAVED_UPDATED is returned depending on the operation performed.
 */
function fbs_save($preset) {

}
